### ISSUE TITLE
The goddamn plugin files disappear every 2 months or so. We should have a more reliable way to fetch those ...

### ISSUE THREAD

**Issue by miloskroulik** [YunoHost-Apps/mediawiki_ynh#31]
It looks like the has at the end of extension package name has been changed...

Please see the logs:

https://paste.yunohost.org/raw/ocomavipay

**Comment by alexAubin** [comment]
Also reported here : https://forum.yunohost.org/t/mediawiki-installation-failure/14024 :/

**Comment by Salamandar** [comment]
Crap, again.
@alexAubin Is there a way to host those files somewhere ? I think I'll push them as release artifacts here on Github.

**Comment by alexAubin** [comment]
Yes we do that kind of thing for wekan which are also crazy about deleting stuff

c.f. https://build.yunohost.org/apps/

But you gotta have access to our infra to do the corresponding wget ...

But if you're willing to make the corresponding changes in app.src etc, i can take 1 minute to copypaste a wget on our server ;)

**Comment by Salamandar** [comment]
@alexAubin For now I wrote a (powerful) script that automatically updates the *.src files from the online list of available Mediawiki extensions. (https://github.com/YunoHost-Apps/mediawiki_ynh/blob/master/update_extensions.py)

Thanks for the idea. Though, I prefer using Github's infrastructure, NOT because I don't trust yours, but because they have a ton of resources to spend and you don't ;)

As my script downloads the files, that'll be easy to automatically push the files to github or your storage.

**Comment by Salamandar** [comment]
Closing for now.

**Comment by Salamandar** [comment]
Reopening. Is there a way for yunohost to email the maintainer (me) when an install failed because of that ? I will be spammed someday but that's still better than an issue on the repo.
